const json = (data, status = 200) => new Response(JSON.stringify(data), {status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const normalize = (value) => String(value || '').trim().toLowerCase().replace(/[يى]/g,'ی').replace(/ك/g,'ک').replace(/[\u200c\u200d]/g,' ').replace(/\s+/g,' ');
const routes = [
{id:'video',keys:['تیزر','ویدیو','فیلم','کلیپ','محتوا ویدیویی'],title:'مسیر تولید تیزر',desc:'از ایده تا نسخه نهایی و آماده انتشار.',steps:['ایده و هدف','سناریو و متن','طراحی تصویر','تولید و تدوین','صدا و نسخه‌ها','انتشار و رشد']},
{id:'website',keys:['سایت','وب سایت','وب‌سایت','وبسایت','فروشگاه','لندینگ','صفحه اینترنتی'],title:'مسیر ساخت سایت',desc:'هدف، ساختار، طراحی، اجرا و رشد را یکجا جلو می‌بریم.',steps:['هدف و مخاطب','ساختار و محتوا','طراحی','توسعه','تست و انتشار','SEO و رشد']},
{id:'prototype',keys:['پیش نمایش','پیش‌نمایش','نمونه قبل','قبل از ساخت','prototype','پروتوتایپ','ماکت'],title:'مسیر پیش‌نمایش',desc:'اول ببین، بررسی کن و اصلاح کن؛ بعد وارد اجرای اصلی شو.',steps:['تعریف ایده','نمونه اولیه','پیش‌نمایش','بازخورد','اصلاح','تأیید نهایی']},
{id:'fix',keys:['خطا','خراب','درست نمی','مشکل','ارور','کند','کار نمی','رفع'],title:'مسیر رفع مشکل',desc:'مشکل را از تشخیص تا تست نهایی دنبال می‌کنیم.',steps:['دریافت مشکل','تشخیص','اولویت‌بندی','راه‌حل','اجرا','تست و تحویل']},
{id:'growth',keys:['فروش','مشتری','رشد','تبلیغ','سئو','seo','بازدید','درآمد'],title:'مسیر رشد',desc:'از هدف کسب‌وکار تا جذب، تبدیل و اندازه‌گیری.',steps:['هدف','مخاطب','پیشنهاد','جذب','تبدیل','اندازه‌گیری']}];
const fallback={id:'custom',title:'مسیر اختصاصی Anil X',desc:'لازم نیست اسم خدمت را بدانی؛ خواسته‌ات را به یک مسیر قابل اجرا تبدیل می‌کنیم.',steps:['فهم خواسته','کشف نیازهای مرتبط','ساخت مسیر','پیش‌نمایش','اجرا','ادامه و رشد']};
export default async (req)=>{if(req.method!=='POST')return json({ok:false,error:'method_not_allowed'},405);try{const body=await req.json();const input=String(body?.text||'').trim().slice(0,1000);if(!input)return json({ok:false,error:'empty_request'},400);const text=normalize(input);const scored=routes.map(route=>({route,score:route.keys.reduce((n,key)=>n+(text.includes(normalize(key))?1:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);const selected=scored[0]?.route||fallback;const confidence=selected===fallback?0.35:Math.min(0.95,0.62+(scored[0].score-1)*0.14);const followUp=selected.id==='custom'?'برای شروع، نتیجه‌ای که می‌خواهی را هم بگو؛ بقیه مسیر را ANIL X جمع می‌کند.':`قدم اول: ${selected.steps[0]} — اگر جزئیات بیشتری داری همین‌جا اضافه کن.`;return json({ok:true,input,route:selected,confidence,followUp,meta:{engine:'anil-x-engine',version:'1.1'}})}catch{return json({ok:false,error:'invalid_json'},400)}};
export const config={path:'/api/analyze'};
