const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const normalize=v=>String(v||'').trim().toLowerCase().replace(/[يى]/g,'ی').replace(/ك/g,'ک').replace(/[\u200c\u200d]/g,' ').replace(/\s+/g,' ');
const routes=[
{id:'video',keys:['video','teaser','تیزر','ویدیو','فیلم','کلیپ'],title:'Video creation path',desc:'From idea to a publish-ready video.',steps:['Goal','Script','Visual direction','Production','Audio and versions','Publish and grow']},
{id:'website',keys:['site','website','store','landing','سایت','فروشگاه','لندینگ','صفحه اینترنتی'],title:'Website build path',desc:'Audience, structure, design, build, launch and growth in one path.',steps:['Audience and goal','Structure and content','Design','Development','QA and launch','SEO and growth']},
{id:'prototype',keys:['prototype','mockup','preview','پیش نمایش','پیش‌نمایش','پروتوتایپ','ماکت'],title:'Prototype path',desc:'See it before committing to the full build.',steps:['Define idea','Prototype','Preview','Feedback','Refine','Approve']},
{id:'fix',keys:['bug','error','fix','broken','slow','خطا','خراب','مشکل','ارور','کند','رفع'],title:'Problem-solving path',desc:'Diagnose, repair and verify the result.',steps:['Capture problem','Diagnose','Prioritize','Fix','Test','Deliver']},
{id:'growth',keys:['sales','customers','growth','seo','traffic','revenue','فروش','مشتری','رشد','سئو','بازدید','درآمد'],title:'Growth path',desc:'Turn a business goal into acquisition, conversion and measurement.',steps:['Goal','Audience','Offer','Acquisition','Conversion','Measurement']}];
const fallback={id:'custom',title:'Adaptive ANIL X path',desc:'You do not need to know the name of the service. ANIL X turns the desired outcome into an executable path.',steps:['Understand outcome','Discover related needs','Build the path','Preview','Execute','Continue and grow']};
const parseJSON=raw=>{try{return JSON.parse(raw)}catch{const m=String(raw||'').match(/\{[\s\S]*\}/);try{return m?JSON.parse(m[0]):null}catch{return null}}};
async function openAI(prompt){const key=process.env.OPENAI_API_KEY;if(!key)return null;const model=process.env.ASTRA_MODEL||'gpt-5.6-sol';const r=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${key}`},body:JSON.stringify({model,messages:[{role:'system',content:'You are Astra, the central ANIL X orchestrator. International-first. Understand the desired outcome, break it into the smallest useful missions, choose the right specialists, and return ONLY JSON: {title,desc,steps,reply,confidence}. Never claim execution without evidence. Prefer English for English users and Persian for Persian users.'},{role:'user',content:prompt}],temperature:.2})});if(!r.ok)throw Error(`openai_${r.status}`);const d=await r.json();return parseJSON(d?.choices?.[0]?.message?.content)}
async function claude(prompt){const key=process.env.ANTHROPIC_API_KEY;if(!key)return null;const model=process.env.CLAUDE_MODEL||'claude-sonnet-5';const r=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'content-type':'application/json','x-api-key':key,'anthropic-version':'2023-06-01'},body:JSON.stringify({model,max_tokens:800,system:'You are ANIL X quality and safety reviewer. Review Astra output. Return ONLY JSON: {ok,corrections,confidence}. Check unsupported claims, contradictions, unsafe actions, missing verification, and poor user fit.',messages:[{role:'user',content:prompt}]})});if(!r.ok)throw Error(`anthropic_${r.status}`);const d=await r.json();return parseJSON(d?.content?.map(x=>x.text||'').join(''))}
async function gemini(prompt){const key=process.env.GEMINI_API_KEY;if(!key)return null;const model=process.env.GEMINI_MODEL||'gemini-3.8-flash';const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(key)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts:[{text:`You are the independent verification and research layer for ANIL X. Review the request and proposed plan independently. Return ONLY JSON: {ok,issues,improvements,confidence}. Do not assume the plan is correct.\n${prompt}`}]}],generationConfig:{responseMimeType:'application/json'}})});if(!r.ok)throw Error(`gemini_${r.status}`);const d=await r.json();return parseJSON(d?.candidates?.[0]?.content?.parts?.map(x=>x.text||'').join(''))}
export default async req=>{if(req.method!=='POST')return json({ok:false,error:'method_not_allowed'},405);try{const body=await req.json();const input=String(body?.text||'').trim().slice(0,4000);if(!input)return json({ok:false,error:'empty_request'},400);const text=normalize(input);const scored=routes.map(route=>({route,score:route.keys.reduce((n,key)=>n+(text.includes(normalize(key))?1:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);const local=scored[0]?.route||fallback;const prompt=JSON.stringify({request:input,language:/[\u0600-\u06ff]/.test(input)?'fa':'en',localRoute:local,profile:body?.profile||{},conversation:Array.isArray(body?.turns)?body.turns.slice(-8):[]});let astra=null,review=null,verification=null;try{astra=await openAI(prompt)}catch{}if(!astra)astra={title:local.title,desc:local.desc,steps:local.steps,reply:/[\u0600-\u06ff]/.test(input)?`گرفتم: ${local.title}`:`Got it: ${local.title}`,confidence:.55};try{review=await claude(JSON.stringify({request:input,astra}))}catch{}try{verification=await gemini(JSON.stringify({request:input,astra,review}))}catch{}const corrections=[...(review?.corrections||[]),...(verification?.issues||[])].filter(Boolean).slice(0,6);if(corrections.length)astra.desc=`${astra.desc||''} ${corrections.join(' ')}`.trim();const confidence=Math.max(.35,Math.min(1,Math.min(Number(astra.confidence)||.7,review?Number(review.confidence)||.7:.7,verification?Number(verification.confidence)||.7:.7)));return json({ok:true,input,route:{id:local.id,title:astra.title||local.title,desc:astra.desc||local.desc,steps:Array.isArray(astra.steps)&&astra.steps.length?astra.steps.slice(0,8):local.steps},reply:astra.reply||local.title,confidence,meta:{engine:'anil-x-ai-council',version:'2.0',internationalFirst:true,orchestrator:astra?'astra':'local',specialists:{claude:Boolean(review),gemini:Boolean(verification)},verification:Boolean(review||verification),fallback:true}})}catch(error){return json({ok:false,error:'engine_failure',message:String(error?.message||error)},502)}};
export const config={path:'/api/analyze'};
