(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const input=$('#requestInput'),form=$('#requestForm'),count=$('#charCount'),result=$('#routeResult'),chat=$('#chat');
const AI_URL='https://anil-x-4j4fxx.v2.appdeploy.ai/api/plan';
const routes=[
{id:'website',keys:['سایت','وب سایت','وب‌سایت','وبسایت','فروشگاه','لندینگ'],title:'ساخت و راه‌اندازی سایت',desc:'از نیازسنجی تا معماری، طراحی، اجرا، تست و رشد.',steps:['فهم هدف','معماری و محتوا','طراحی','توسعه','تست و انتشار','SEO و رشد']},
{id:'video',keys:['تیزر','ویدیو','فیلم','کلیپ','محتوا'],title:'تولید محتوای ویدیویی',desc:'ایده را به سناریو، تصویر، صدا، تدوین و خروجی انتشار تبدیل می‌کنیم.',steps:['هدف','سناریو','استایل بصری','تولید','تدوین','انتشار']},
{id:'fix',keys:['خطا','خراب','درست نمی','مشکل','ارور','کند','کار نمی'],title:'تشخیص و رفع مشکل',desc:'اول علت را جدا می‌کنیم، بعد اصلاح را اجرا و نتیجه را تست می‌کنیم.',steps:['دریافت شواهد','تشخیص','اولویت','راه‌حل','اصلاح','تست نهایی']},
{id:'growth',keys:['فروش','مشتری','رشد','تبلیغ','سئو','بازدید','درآمد'],title:'موتور رشد کسب‌وکار',desc:'هدف، مشتری، پیشنهاد، جذب، تبدیل و اندازه‌گیری در یک مسیر.',steps:['هدف','مخاطب','پیشنهاد','جذب','تبدیل','اندازه‌گیری']},
{id:'prototype',keys:['پیش نمایش','پیش‌نمایش','نمونه قبل','ماکت'],title:'پیش‌نمایش قبل از اجرا',desc:'قبل از هزینه و اجرای کامل، نتیجه را قابل مشاهده و قابل اصلاح می‌کنیم.',steps:['ایده','نمونه','پیش‌نمایش','بازخورد','اصلاح','تأیید']}];
const fallback={id:'custom',title:'مسیر اختصاصی ANIL X',desc:'خواسته‌ات را به یک برنامه اجرایی قابل فهم تبدیل می‌کنیم.',steps:['فهم خواسته','کشف نیاز','ساخت مسیر','پیش‌نمایش','اجرا','اندازه‌گیری']};
const normalize=s=>String(s||'').trim().toLowerCase().replace(/[يى]/g,'ی').replace(/ك/g,'ک').replace(/[\u200c\u200d]/g,' ').replace(/\s+/g,' ');
const findRoute=t=>{const x=normalize(t);return routes.find(r=>r.keys.some(k=>x.includes(normalize(k))))||fallback};
let profile={age:'',goal:''};try{profile=JSON.parse(localStorage.getItem('anilx_profile')||'{}')}catch{}
const ageNames={child:'کودک',teen:'نوجوان',young:'جوان',adult:'بزرگسال',senior:'بزرگسال ارشد'};
const goalNames={learn:'یادگیری',business:'کسب‌وکار',create:'ساختن و خلق کردن',fix:'رفع مشکل',curious:'کشف ANIL X'};
function updateCount(){if(count&&input)count.textContent=`${input.value.length} / 4000`}
function addMsg(who,text){if(!chat)return null;const d=document.createElement('div');d.className=`msg ${who}`;const b=document.createElement('b');b.textContent=who==='bot'?'آنیل':'تو';const p=document.createElement('p');p.textContent=text;d.append(b,p);chat.appendChild(d);chat.scrollTop=chat.scrollHeight;return p}
function renderRoute(route){if(!result)return;result.innerHTML='';const h=document.createElement('h3');h.textContent=route.title;const p=document.createElement('p');p.textContent=route.desc;const badge=document.createElement('div');badge.className='route-badge';badge.textContent=`مسیر شخصی‌سازی‌شده · ${ageNames[profile.age]||'عمومی'} · ${goalNames[profile.goal]||'هدف آزاد'}`;const ul=document.createElement('ol');ul.className='route-list';route.steps.forEach(s=>{const li=document.createElement('li');li.textContent=s;ul.appendChild(li)});result.append(h,p,badge,ul);result.hidden=false;result.scrollIntoView({behavior:'smooth',block:'nearest'})}
function localAnswer(text,route){const t=normalize(text);if(route.id==='fix')return'اول شواهد مشکل را جمع می‌کنم، علت اصلی را از علامت ظاهری جدا می‌کنم و بعد فقط اصلاح لازم را پیشنهاد می‌دهم. اگر فایل، عکس یا متن خطا داری همین‌جا اضافه کن.';if(route.id==='website')return'سایت را از نتیجه‌ای که باید بسازد شروع می‌کنیم؛ ساختار، تجربه کاربر، اجرا، تست و رشد باید از اول یک زنجیره باشند.';if(route.id==='growth')return'برای رشد، اول عدد هدف و مشتری را مشخص می‌کنیم؛ بعد پیشنهاد، کانال جذب، تبدیل و اندازه‌گیری را می‌چینیم.';if(route.id==='video')return'تیزر را از هدف و مخاطب شروع می‌کنیم، نه از ابزار؛ بعد سناریو، تصویر، صدا و نسخه‌های انتشار را می‌سازیم.';if(t.includes('چی کار')||t.includes('چکار'))return'اول خواسته‌ات را به چند کار مشخص تبدیل می‌کنم؛ بعد مسیر اجرا و نتیجه قابل اندازه‌گیری را نشان می‌دهم.';return'گرفتم. خواسته‌ات را به مسیر اجرایی تبدیل می‌کنم و اگر جایی نیاز به انسان، ابزار یا تأیید واقعی باشد همان‌جا مشخصش می‌کنم.'}
function enginePanel(mode){let p=$('#anilEnginePanel');if(p)return p;p=document.createElement('div');p.id='anilEnginePanel';p.style.cssText='margin:12px 16px 0;padding:11px 13px;border:1px solid rgba(216,173,79,.16);border-radius:16px;background:linear-gradient(90deg,rgba(216,173,79,.055),rgba(112,170,178,.045));color:#a99d88;font-size:10px;display:flex;align-items:center;gap:10px;flex-wrap:wrap';p.innerHTML=`<span style="width:7px;height:7px;border-radius:50%;background:#9dcc8f;box-shadow:0 0 10px #9dcc8f"></span><b style="color:#e2c27e">ANIL X ENGINE</b><span id="engineMode">${mode||'adaptive'}</span><span style="margin-inline-start:auto">فهم → برنامه‌ریزی → بازبینی → اقدام</span>`;const a=$('.assistant-head');a?.parentNode.insertBefore(p,a.nextSibling);return p}
async function callAI(request){const r=await fetch(AI_URL,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(request)});if(!r.ok)throw new Error(`AI ${r.status}`);const data=await r.json();return data?.text||data?.answer||data?.result||''}
async function askAI(text,route,attachment){const base={request:`تو موتور ANIL X هستی. نقش تو فقط چت‌کردن نیست: خواسته را بفهم، نوع کار را تشخیص بده، برنامه اجرایی بده، محدودیت‌ها و مرز انسان را مشخص کن و از ادعای انجام کاری که واقعاً انجام نشده خودداری کن. پاسخ فارسی و روشن باشد. کاربر: ${text}\nمسیر تشخیص‌داده‌شده: ${route.id}\nسن: ${ageNames[profile.age]||'نامشخص'}\nهدف: ${goalNames[profile.goal]||'نامشخص'}${attachment?`\nفایل انتخاب‌شده: ${attachment}`:''}`,language:/[\u0600-\u06ff]/.test(text)?'fa':'en',age:profile.age==='child'?8:profile.age==='teen'?15:profile.age==='young'?24:profile.age==='adult'?42:profile.age==='senior'?68:undefined,ageProfile:profile.age||'adult',vision:'default',currency:'USD',deviceWidth:window.innerWidth};
enginePanel(route.id==='fix'?'diagnostic':route.id==='growth'?'growth':'adaptive');
const first=await callAI(base);if(!first)return'';
const complex=['fix','website','growth','prototype'].includes(route.id)||text.length>120;
if(!complex)return first;
try{const review=await callAI({...base,request:`این پاسخ اولیه ANIL X است:\n${first}\n\nاکنون مثل یک بازبین ارشد آن را بررسی کن. موارد مبهم، وعده غیرواقعی، قدم‌های جاافتاده و ریسک‌ها را اصلاح کن و یک نسخه نهایی کوتاه و اجرایی بده. اگر کاری بدون دسترسی واقعی قابل انجام نیست، دقیقاً بگو چه چیزی لازم است.`});return review||first}catch{return first}}
async function handle(text){const value=String(text||'').trim();if(!value||!input)return;addMsg('user',value);const pending=addMsg('bot','در حال فهم خواسته و ساخت مسیر…');const route=findRoute(value);const file=$('#imageInput')?.files?.[0];const attachment=file?`${file.name} (${Math.round(file.size/1024)}KB)`:'';let aiText='';try{aiText=await askAI(value,route,attachment)}catch{}
if(pending){pending.textContent=aiText||localAnswer(value,route)}renderRoute(route);input.value='';updateCount()}
$$('[data-request],[data-chat]').forEach(c=>c.addEventListener('click',()=>{if(input){input.value=c.dataset.request||c.dataset.chat||'';updateCount();handle(input.value)}}));input?.addEventListener('input',updateCount);form?.addEventListener('submit',e=>{e.preventDefault();handle(input?.value||'')});
const voice=$('#voiceBtn'),status=$('#voiceStatus');if(voice&&('webkitSpeechRecognition'in window||'SpeechRecognition'in window)){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;const rec=new SR();rec.lang='fa-IR';rec.interimResults=false;voice.addEventListener('click',()=>{try{rec.start();voice.setAttribute('aria-pressed','true');if(status){status.hidden=false;status.textContent='در حال شنیدن…'}}catch{}});rec.onresult=e=>{if(input){input.value=e.results[0][0].transcript;updateCount();handle(input.value)}if(status)status.textContent='گرفتم.'};rec.onerror=()=>{voice.setAttribute('aria-pressed','false');if(status){status.hidden=false;status.textContent='ورودی صوتی در این مرورگر در دسترس نیست.'}};rec.onend=()=>voice.setAttribute('aria-pressed','false')}else voice?.addEventListener('click',()=>{if(status){status.hidden=false;status.textContent='ورودی صوتی در این مرورگر در دسترس نیست.'}});
const image=$('#imageInput'),preview=$('#imagePreview');image?.addEventListener('change',()=>{const f=image.files?.[0];if(!f)return;preview.hidden=false;preview.textContent=`فایل «${f.name}» آماده شد. توضیحت را اضافه کن تا آن را در مسیر کار لحاظ کنم.`;input?.focus()});
const modal=$('#profileModal'),ageGrid=$('#ageGrid'),goalGrid=$('#goalGrid'),save=$('#saveProfile'),close=$('#closeProfile'),profileBtn=$('#profileBtn'),change=$('#changeProfile');
function syncProfileUI(){ $$('[data-age]').forEach(b=>b.classList.toggle('active',b.dataset.age===profile.age));$$('[data-goal]').forEach(b=>b.classList.toggle('active',b.dataset.goal===profile.goal));if(save)save.disabled=!(profile.age&&profile.goal);const badge=$('#audienceBadge'),line=$('#welcomeLine');if(badge)badge.textContent=profile.age?`${ageNames[profile.age]} · ${goalNames[profile.goal]||'تجربه شخصی'}`:'تجربه شخصی تو';if(line)line.textContent=profile.age?`تجربه تو آماده است: ${ageNames[profile.age]} · ${goalNames[profile.goal]}`:'اول خودت را به ANIL X معرفی کن.'}
const openProfile=()=>{if(modal)modal.hidden=false},closeProfile=()=>{if(modal)modal.hidden=true};ageGrid?.addEventListener('click',e=>{const b=e.target.closest('[data-age]');if(b){profile.age=b.dataset.age;syncProfileUI()}});goalGrid?.addEventListener('click',e=>{const b=e.target.closest('[data-goal]');if(b){profile.goal=b.dataset.goal;syncProfileUI()}});save?.addEventListener('click',()=>{localStorage.setItem('anilx_profile',JSON.stringify(profile));closeProfile();syncProfileUI()});close?.addEventListener('click',closeProfile);profileBtn?.addEventListener('click',openProfile);change?.addEventListener('click',openProfile);modal?.addEventListener('click',e=>{if(e.target===modal)closeProfile()});updateCount();syncProfileUI();if(!profile.age||!profile.goal)setTimeout(openProfile,650);
function createRoyalDetails(){
const style=document.createElement('style');style.textContent=`.ax-control{position:fixed;z-index:80;left:16px;bottom:16px;display:flex;flex-direction:column;gap:8px}.ax-control button{border:1px solid rgba(216,173,79,.45);background:rgba(8,6,4,.88);backdrop-filter:blur(14px);color:#f0d18a;border-radius:999px;padding:9px 13px;font-size:11px;box-shadow:0 8px 30px rgba(0,0,0,.35)}.ax-control button:hover{transform:translateY(-2px);border-color:#ffe0a0}.ax-inspect *{transition:filter .2s ease}.ax-inspect .heritage-card,.ax-inspect .service-grid article,.ax-inspect .future-card{outline:1px solid rgba(216,173,79,.16)}.ax-inspect .ax-hidden-detail{opacity:1!important;transform:none!important}.ax-hidden-detail{opacity:.035;transform:scale(.97);transition:all .35s ease;cursor:pointer}.ax-hidden-detail:hover{opacity:1}.ax-riddle{position:fixed;z-index:90;inset:0;display:grid;place-items:center;background:rgba(3,2,1,.76);backdrop-filter:blur(8px)}.ax-riddle[hidden]{display:none}.ax-riddle-card{width:min(430px,90vw);padding:28px;border:1px solid rgba(216,173,79,.4);border-radius:28px;background:linear-gradient(145deg,#1b1208,#080706);text-align:center;box-shadow:0 30px 100px #000}.ax-riddle-card h3{color:#ffe0a0;margin:0 0 8px}.ax-riddle-card p{color:#b9aa90;font-size:12px}.ax-riddle-card input{width:100%;box-sizing:border-box;background:#0d0905;border:1px solid rgba(216,173,79,.25);color:#fff8e8;border-radius:13px;padding:10px;text-align:center}.ax-riddle-card button{margin-top:10px;border:1px solid rgba(216,173,79,.35);background:#171008;color:#ffe0a0;border-radius:12px;padding:9px 14px}.ax-secret{position:fixed;z-index:70;pointer-events:none;font-size:8px;letter-spacing:.35em;color:rgba(255,224,160,.25);opacity:0;animation:axfade 5s ease forwards}@keyframes axfade{0%,80%{opacity:0}35%,65%{opacity:.8}100%{opacity:0}}`;
document.head.appendChild(style);
const controls=document.createElement('div');controls.className='ax-control';controls.innerHTML='<button id="axInspect">🔎 عینک کاوش</button><button id="axAdmin">♛ مرکز مدیریت</button><button id="axRiddle">✦ راز پارسه</button>';document.body.appendChild(controls);
$('#axAdmin').onclick=()=>location.href='admin.html';
let inspecting=false;$('#axInspect').onclick=()=>{inspecting=!inspecting;document.body.classList.toggle('ax-inspect',inspecting);$('#axInspect').textContent=inspecting?'🔎 عینک روشن · جزئیات پیدا کن':'🔎 عینک کاوش'};
const details=[['heritage-card','𐎠'],['service-grid article','01'],['future-card','AX'],['promise','◇']];details.forEach(([sel,sym],i)=>{document.querySelectorAll('.'+sel.replace(' ',' .')).forEach((el,n)=>{const d=document.createElement('span');d.className='ax-hidden-detail';d.textContent=`  ${sym}  ${['ANIL','PARSA','CROWN','X'][i]}  `;d.style.position='absolute';d.style.right=(8+n*13)+'%';d.style.top=(12+n*9)+'%';d.style.fontSize='8px';d.style.letterSpacing='.25em';el.style.position='relative';el.appendChild(d)})});
const riddle=document.createElement('div');riddle.className='ax-riddle';riddle.hidden=true;riddle.innerHTML='<div class="ax-riddle-card"><h3>راز پارسه</h3><p>سه نماد در این شهر پنهان شده. اگر پیدایشان کردی، کلمه‌ای را وارد کن که ANIL X را باز می‌کند.</p><div style="font-size:28px;color:#d8ad4f;margin:12px">𐎠 · ✦ · X</div><input id="axAnswer" placeholder="کلمه رمز"><button id="axCheck">باز کردن</button><button id="axClose">بستن</button><p id="axResult"></p></div>';document.body.appendChild(riddle);$('#axRiddle').onclick=()=>riddle.hidden=false;$('#axClose').onclick=()=>riddle.hidden=true;$('#axCheck').onclick=()=>{const v=normalize($('#axAnswer').value);const ok=['انسان','انسانیت','human','anil x'].includes(v);$('#axResult').textContent=ok?'دروازه باز شد. یک لایه دیگر از شهر برایت آشکار شد.':'هنوز نه؛ بیشتر دقت کن. خود شهر راهنمایت می‌کند.';if(ok){localStorage.setItem('anilx_secret_unlocked','1');document.body.classList.add('ax-inspect');inspecting=true;$('#axInspect').textContent='🔎 عینک روشن · جزئیات پیدا کن'}};
setInterval(()=>{if(Math.random()>.55)return;const s=document.createElement('span');s.className='ax-secret';s.textContent=['AX · 𐎠 · 𓂀','سه بار نگاه کن','PARSA · 2500+','ANIL X'][Math.floor(Math.random()*4)];s.style.left=(8+Math.random()*84)+'vw';s.style.top=(12+Math.random()*70)+'vh';document.body.appendChild(s);setTimeout(()=>s.remove(),5200)},11000);
}
createRoyalDetails();
async function initWallet(){try{const{TonConnectUI}=await import('https://cdn.jsdelivr.net/npm/@tonconnect/ui@2.3.6/+esm');const manifest='https://saberbadri24-tech.github.io/city-of-eternity/tonconnect-manifest.json';const ui=new TonConnectUI({manifestUrl:manifest});const box=document.createElement('section');box.id='wallet';box.style.cssText='width:min(900px,100%);margin:28px auto 0;padding:18px;border:1px solid rgba(216,173,79,.32);border-radius:22px;background:linear-gradient(145deg,rgba(28,21,13,.96),rgba(9,9,8,.94));text-align:right';box.innerHTML='<div style="display:flex;align-items:center;justify-content:space-between;gap:14px;flex-wrap:wrap"><div><div style="font-size:10px;letter-spacing:.18em;color:#d8ad4f;font-weight:800">ANIL X WALLET</div><h3 style="margin:4px 0;color:#f0d18a">TON · Tonkeeper</h3><p id="walletStatus" style="margin:0;color:#a99d88;font-size:12px">کیف پول شخصی خودت را وصل کن؛ عبارت بازیابی داخل Tonkeeper می‌ماند.</p></div><div id="tonConnectButton"></div></div><div id="walletAddress" style="margin-top:10px;color:#8f856f;font-size:11px;word-break:break-all"></div>';const anchor=$('.future')||$('.heritage');if(anchor)anchor.parentNode.insertBefore(box,anchor);ui.onStatusChange(wallet=>{const st=$('#walletStatus'),addr=$('#walletAddress');if(wallet){const a=wallet.account?.address||'';if(st)st.textContent='کیف پول وصل شد. تأیید تراکنش‌ها داخل خود کیف پول انجام می‌شود.';if(addr)addr.textContent=a?`آدرس متصل: ${a}`:'';localStorage.setItem('anilx_ton_wallet',a)}else{if(st)st.textContent='کیف پول شخصی خودت را وصل کن؛ عبارت بازیابی داخل Tonkeeper می‌ماند.';if(addr)addr.textContent='';localStorage.removeItem('anilx_ton_wallet')}});ui.connector?.restoreConnection?.()}catch(e){console.warn('TON Connect unavailable',e)}}
initWallet();
})();