(()=>{'use strict';
const LANGS={en:['English','ltr'],fa:['فارسی','rtl'],ar:['العربية','rtl'],tr:['Türkçe','ltr'],ru:['Русский','ltr'],de:['Deutsch','ltr'],fr:['Français','ltr'],es:['Español','ltr'],pt:['Português','ltr'],it:['Italiano','ltr'],nl:['Nederlands','ltr'],pl:['Polski','ltr'],uk:['Українська','ltr'],sv:['Svenska','ltr'],no:['Norsk','ltr'],da:['Dansk','ltr'],fi:['Suomi','ltr'],cs:['Čeština','ltr'],sk:['Slovenčina','ltr'],ro:['Română','ltr'],hu:['Magyar','ltr'],el:['Ελληνικά','ltr'],bg:['Български','ltr'],sr:['Срpski','ltr'],hr:['Hrvatski','ltr'],sl:['Slovenščina','ltr'],he:['עברית','rtl'],ur:['اردو','rtl'],hi:['हिन्दी','ltr'],bn:['বাংলা','ltr'],ta:['தமிழ்','ltr'],te:['తెలుగు','ltr'],th:['ไทย','ltr'],vi:['Tiếng Việt','ltr'],id:['Bahasa Indonesia','ltr'],ms:['Bahasa Melayu','ltr'],'zh-CN':['中文简体','ltr'],'zh-TW':['中文繁體','ltr'],ja:['日本語','ltr'],ko:['한국어','ltr']};
const KEY='anilx-language-v3',CACHE='anilx-i18n-cache-v3',original=new Map(),translated=new Map();
const esc=s=>String(s).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
const get=()=>{const q=new URLSearchParams(location.search).get('lang');if(q&&LANGS[q])return q;const saved=localStorage.getItem(KEY);return saved&&LANGS[saved]?saved:'en'};
let lang=get();window.ANILX_LANGUAGE=lang;
const cache=(()=>{try{return JSON.parse(localStorage.getItem(CACHE)||'{}')}catch{return {}}})();
function setup(){document.documentElement.lang=lang;document.documentElement.dir=LANGS[lang][1];if(document.querySelector('#axLanguage'))return;const host=document.querySelector('.top-actions')||document.querySelector('.nav')||document.querySelector('header');if(!host)return;const box=document.createElement('label');box.id='axLanguage';box.style.cssText='display:inline-flex;align-items:center;gap:5px;margin-inline:4px';box.innerHTML='<span style="font-size:12px;opacity:.7">🌐</span><select aria-label="Language" style="border:1px solid rgba(216,173,79,.3);background:#0c0906;color:#ffe7ad;border-radius:999px;padding:7px 10px;font:inherit;max-width:145px">'+Object.entries(LANGS).map(([k,v])=>'<option value="'+esc(k)+'">'+esc(v[0])+'</option>').join('')+'</select>';host.prepend(box);box.querySelector('select').value=lang;box.querySelector('select').addEventListener('change',e=>switchLang(e.target.value))}
function nodes(){const out=[];const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT,{acceptNode(n){const p=n.parentElement;if(!p||/^(SCRIPT|STYLE|NOSCRIPT|TEXTAREA|OPTION|CODE|SELECT)$/.test(p.tagName))return NodeFilter.FILTER_REJECT;const t=n.nodeValue.trim();if(t.length<2||/^([←→·•|/]+)$/.test(t))return NodeFilter.FILTER_REJECT;return NodeFilter.FILTER_ACCEPT}});while(w.nextNode())out.push(w.currentNode);return out}
function remember(){nodes().forEach(n=>{if(!original.has(n))original.set(n,n.nodeValue)});document.querySelectorAll('input[placeholder],textarea[placeholder]').forEach(n=>{if(!original.has(n))original.set(n,n.getAttribute('placeholder')||'')})}
function visible(n){const el=n?.nodeType===1?n:n?.parentElement;if(!el||typeof el.getBoundingClientRect!=='function')return false;const r=el.getBoundingClientRect();return r.bottom>=0&&r.top<=innerHeight&&r.right>=0&&r.left<=innerWidth}
function restore(){for(const n of nodes()){const t=original.get(n);if(t&&n.nodeValue.trim()!==t.trim())n.nodeValue=t}document.querySelectorAll('input[placeholder],textarea[placeholder]').forEach(n=>{const t=original.get(n);if(t!==undefined)n.setAttribute('placeholder',t)})}
async function translateBatch(items,target){if(!items.length)return;const fresh=[];for(const x of items){const k=target+'|'+x;if(translated.has(k))continue;if(cache[k]!==undefined){translated.set(k,cache[k]);continue}fresh.push(x)}if(!fresh.length)return;const joined=fresh.map((x,i)=>'[[AX'+i+']] '+x).join('\n');const r=await fetch('/api/translate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text:joined,target}),cache:'no-store'});if(!r.ok)throw Error('translate_'+r.status);const d=await r.json();if(!d.ok)throw Error('translate_failed');const lines=String(d.text||'').split('\n');for(let i=0;i<fresh.length;i++){const marker='[[AX'+i+']]';const line=lines.find(x=>x.includes(marker));const value=line?line.slice(line.indexOf(marker)+marker.length).trim():fresh[i];const k=target+'|'+fresh[i];translated.set(k,value);cache[k]=value}try{localStorage.setItem(CACHE,JSON.stringify(cache))}catch{}}
async function apply(target){remember();restore();document.documentElement.lang=target;document.documentElement.dir=LANGS[target][1];window.ANILX_LANGUAGE=target;if(target==='en')return;
 const ns=nodes(),seen=new Set(),items=[],refs=[];
 const max=innerWidth<700?10:14;
 for(const n of ns){if(items.length>=max)break;const t=(original.get(n)||n.nodeValue).trim();if(!t||seen.has(t)||!visible(n))continue;seen.add(t);items.push(t);refs.push(n)}
 const ph=[...document.querySelectorAll('input[placeholder],textarea[placeholder]')].map(n=>({n,t:original.get(n)||''})).filter(x=>x.t&&!seen.has(x.t)).slice(0,2);
 for(const x of ph){if(items.length>=max)break;seen.add(x.t);items.push(x.t);refs.push(x.n)}
 try{await translateBatch(items,target);refs.forEach((n,i)=>{const t=items[i],v=translated.get(target+'|'+t);if(v){if(n.nodeType===3)n.nodeValue=n.nodeValue.replace(t,v);else n.setAttribute('placeholder',v)}})}catch{}
}
async function switchLang(next){if(!LANGS[next]||next===lang)return;lang=next;localStorage.setItem(KEY,next);const u=new URL(location.href);u.searchParams.set('lang',next);history.replaceState({},'',u);setup();await apply(next);window.dispatchEvent(new CustomEvent('anilx:language',{detail:{language:next}}))}
function boot(){setup();remember();window.ANILX_LANGUAGE=lang;if(lang!=='en'){const idle=window.requestIdleCallback||((f)=>setTimeout(f,700));idle(()=>apply(lang).catch(()=>{}),{timeout:1500})}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();