(()=>{'use strict';
const LANGS={en:['English','ltr'],fa:['فارسی','rtl'],ar:['العربية','rtl'],tr:['Türkçe','ltr'],ru:['Русский','ltr'],de:['Deutsch','ltr'],fr:['Français','ltr'],es:['Español','ltr'],pt:['Português','ltr'],it:['Italiano','ltr'],nl:['Nederlands','ltr'],pl:['Polski','ltr'],uk:['Українська','ltr'],sv:['Svenska','ltr'],no:['Norsk','ltr'],da:['Dansk','ltr'],fi:['Suomi','ltr'],cs:['Čeština','ltr'],sk:['Slovenčina','ltr'],ro:['Română','ltr'],hu:['Magyar','ltr'],el:['Ελληνικά','ltr'],bg:['Български','ltr'],sr:['Срپски','ltr'],hr:['Hrvatski','ltr'],sl:['Slovenščina','ltr'],he:['עברית','rtl'],ur:['اردو','rtl'],hi:['हिन्दी','ltr'],bn:['বাংলা','ltr'],ta:['தமிழ்','ltr'],te:['తెలుగు','ltr'],th:['ไทย','ltr'],vi:['Tiếng Việt','ltr'],id:['Bahasa Indonesia','ltr'],ms:['Bahasa Melayu','ltr'],'zh-CN':['中文简体','ltr'],'zh-TW':['中文繁體','ltr'],ja:['日本語','ltr'],ko:['한국어','ltr']};
const KEY='anilx-language-v3',CACHE='anilx-i18n-cache-v3';
const esc=s=>String(s).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
const get=()=>{const q=new URLSearchParams(location.search).get('lang');if(q&&LANGS[q])return q;const saved=localStorage.getItem(KEY);if(saved&&LANGS[saved])return saved;return 'en'};
let lang=get();window.ANILX_LANGUAGE=lang;
const original=new Map(),cache=(()=>{try{return JSON.parse(localStorage.getItem(CACHE)||'{}')}catch{return {}}})();
function setup(){document.documentElement.lang=lang;document.documentElement.dir=LANGS[lang][1];if(document.querySelector('#axLanguage'))return;
 const host=document.querySelector('.top-actions')||document.querySelector('.nav')||document.querySelector('header');if(!host)return;
 const box=document.createElement('label');box.id='axLanguage';box.style.cssText='display:inline-flex;align-items:center;gap:5px;margin-inline:4px';
 box.innerHTML='<span style="font-size:12px;opacity:.7">🌐</span><select aria-label="Language" style="border:1px solid rgba(216,173,79,.3);background:#0c0906;color:#ffe7ad;border-radius:999px;padding:7px 10px;font:inherit;max-width:145px">'+Object.entries(LANGS).map(([k,v])=>'<option value="'+esc(k)+'">'+esc(v[0])+'</option>').join('')+'</select>';
 host.prepend(box);box.querySelector('select').value=lang;box.querySelector('select').addEventListener('change',e=>switchLang(e.target.value));
}
function nodes(){const out=[];const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT,{acceptNode(n){const p=n.parentElement;if(!p||/^(SCRIPT|STYLE|NOSCRIPT|TEXTAREA|OPTION|CODE)$/.test(p.tagName))return NodeFilter.FILTER_REJECT;const t=n.nodeValue.trim();if(t.length<2||/^([←→·•|/]+)$/.test(t))return NodeFilter.FILTER_REJECT;return NodeFilter.FILTER_ACCEPT}});while(w.nextNode())out.push(w.currentNode);return out}
function remember(){nodes().forEach(n=>{if(!original.has(n))original.set(n,n.nodeValue)});document.querySelectorAll('input[placeholder],textarea[placeholder]').forEach(n=>{if(!original.has(n))original.set(n,n.getAttribute('placeholder')||'')})}
async function translateBatch(items,target){const joined=items.map((x,i)=>'[[AX'+i+']] '+x).join('\n');const r=await fetch('/api/translate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text:joined,target}),cache:'no-store'});const d=await r.json();if(!d.ok)return items;const lines=String(d.text||'').split('\n'),out=new Array(items.length).fill('');for(let i=0;i<items.length;i++){const marker='[[AX'+i+']]';const line=lines.find(x=>x.includes(marker));if(line)out[i]=line.slice(line.indexOf(marker)+marker.length).trim()}return out.map((x,i)=>x||items[i])}
async function apply(target){remember();for(const n of nodes())n.nodeValue=original.get(n)||n.nodeValue;document.querySelectorAll('input[placeholder],textarea[placeholder]').forEach(n=>n.setAttribute('placeholder',original.get(n)||n.getAttribute('placeholder')||''));
 const ns=nodes(),unique=[...new Set(ns.map(n=>(original.get(n)||n.nodeValue).trim()).filter(Boolean))],translated={};
 const batches=[];for(let i=0;i<unique.length;){let part=[],size=0;while(i<unique.length&&part.length<12&&size+unique[i].length<1800){part.push(unique[i]);size+=unique[i].length+8;i++}if(part.length)batches.push(part)}
 for(let i=0;i<batches.length;i+=4){const group=batches.slice(i,i+4);await Promise.all(group.map(async part=>{const missing=part.filter(t=>translated[t]===undefined);if(!missing.length)return;const key=target+'|'+missing.join('\n');if(cache[key]){missing.forEach((x,j)=>translated[x]=cache[key].split('\n')[j]||x);return}try{const got=await translateBatch(missing,target);got.forEach((x,j)=>translated[missing[j]]=x);cache[key]=got.join('\n')}catch{missing.forEach(x=>translated[x]=x)}}));try{localStorage.setItem(CACHE,JSON.stringify(cache))}catch{}}
 ns.forEach(n=>{const t=(original.get(n)||n.nodeValue).trim();if(translated[t])n.nodeValue=n.nodeValue.replace(t,translated[t])});
 const placeholders=[...document.querySelectorAll('input[placeholder],textarea[placeholder]')].map(n=>({n,t:original.get(n)||''})).filter(x=>x.t);if(placeholders.length){try{const got=await translateBatch(placeholders.map(x=>x.t),target);placeholders.forEach((x,i)=>x.n.setAttribute('placeholder',got[i]||x.t))}catch{}}
 document.documentElement.lang=target;document.documentElement.dir=LANGS[target][1];window.ANILX_LANGUAGE=target}
async function switchLang(next){if(!LANGS[next])return;lang=next;localStorage.setItem(KEY,next);const u=new URL(location.href);u.searchParams.set('lang',next);history.replaceState({},'',u);setup();await apply(next);window.dispatchEvent(new CustomEvent('anilx:language',{detail:{language:next}}))}
function boot(){setup();window.ANILX_LANGUAGE=lang;const hasSourceFa=/[\u0600-\u06ff]/.test(document.body?.innerText||'');if(lang==='fa'&&hasSourceFa)return;if(lang==='en'&&!hasSourceFa)return;const idle=window.requestIdleCallback||((f)=>setTimeout(f,80));idle(()=>setTimeout(()=>apply(lang).catch(()=>{}),350),{timeout:1800})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();