const H={'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*','access-control-allow-methods':'POST,OPTIONS','access-control-allow-headers':'content-type'};
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:H});
const text=v=>String(v||'').trim();
const localPlan=input=>{const t=text(input).toLowerCase();const rules=[[['site','website','سایت','وب سایت','وب‌سایت','فروشگاه'],'website','ساخت و راه‌اندازی سایت'],[['video','teaser','تیزر','ویدیو'],'video','تولید محتوای ویدیویی'],[['bug','error','fix','خطا','خراب','مشکل','ارور'],'fix','تشخیص و رفع مشکل'],[['sales','growth','seo','فروش','مشتری','رشد','سئو'],'growth','موتور رشد کسب‌وکار'],[['preview','prototype','پیش‌نمایش','ماکت'],'preview','پیش‌نمایش قبل از اجرا']];const hit=rules.find(([keys])=>keys.some(k=>t.includes(k)));return {title:hit?.[2]||'مسیر اختصاصی ANIL X',desc:'مسیر بر اساس خواسته فعلی ساخته می‌شود.',moves:hit?['فهم نتیجه','انتخاب متخصص','اجرا','بررسی و اصلاح']:['شفاف‌کردن نتیجه','کشف بهترین اقدام','پیش‌نمایش','اجرا']};};
async function toolWebSearch(env,query){
  if(!env.TAVILY_API_KEY&&!env.BRAVE_SEARCH_API_KEY)return {ok:false,error:'web_search_key_not_configured'};
  try{
    if(env.TAVILY_API_KEY){
      const r=await fetch('https://api.tavily.com/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({api_key:env.TAVILY_API_KEY,query:String(query).slice(0,500),max_results:5,search_depth:'basic'})});
      return {ok:r.ok,provider:'tavily',data:await r.json().catch(()=>null)};
    }
    const r=await fetch('https://api.search.brave.com/res/v1/web/search?q='+encodeURIComponent(String(query).slice(0,500))+'&count=5',{headers:{accept:'application/json','X-Subscription-Token':env.BRAVE_SEARCH_API_KEY}});
    return {ok:r.ok,provider:'brave',data:await r.json().catch(()=>null)};
  }catch(e){return {ok:false,error:String(e?.message||e)}}
}
async function toolFetchUrl(env,url){
  try{
    const u=new URL(url);
    if(!/^https?:$/.test(u.protocol)||/localhost$|^127\\.|^10\\.|^192\\.168\\.|^169\\.254\\.|^172\\.(1[6-9]|2\\d|3[0-1])\\./i.test(u.hostname))return {ok:false,error:'url_not_allowed'};
    const r=await fetch(u,{redirect:'follow',headers:{'user-agent':'ANIL-X-Agent/1.0'}});
    const ct=r.headers.get('content-type')||'';
    const raw=(await r.text()).slice(0,30000);
    const body=ct.includes('html')?raw.replace(/<script[\\s\\S]*?<\\/script>/gi,' ').replace(/<style[\\s\\S]*?<\\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\\s+/g,' ').trim().slice(0,10000):raw.slice(0,10000);
    return {ok:r.ok,status:r.status,url:r.url,title:(raw.match(/<title[^>]*>([\\s\\S]*?)<\\/title>/i)?.[1]||'').trim().slice(0,200),body};
  }catch(e){return {ok:false,error:String(e?.message||e)}}
}
const extract=raw=>{try{return JSON.parse(raw)}catch{const m=String(raw||'').match(/\\{[\\s\\S]*\\}/);try{return m?JSON.parse(m[0]):null}catch{return null}}};
async function openai(env,prompt){if(!env.OPENAI_API_KEY)return null;const r=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+env.OPENAI_API_KEY},body:JSON.stringify({model:env.ASTRA_MODEL||'gpt-5-mini',messages:[{role:'system',content:'You are Astra, central ANIL X orchestrator. Return JSON only: title,desc,moves,reply,confidence,specialist. Never claim execution without evidence.'},{role:'user',content:prompt}],temperature:.2})});if(!r.ok)throw Error('openai_'+r.status);const d=await r.json();return extract(d?.choices?.[0]?.message?.content)}
async function claude(env,prompt){if(!env.ANTHROPIC_API_KEY)return null;const r=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'content-type':'application/json','x-api-key':env.ANTHROPIC_API_KEY,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:env.CLAUDE_MODEL||'claude-sonnet-4-5',max_tokens:700,system:'You are Claude, ANIL X engineering reviewer. Return JSON only with ok,corrections,confidence.',messages:[{role:'user',content:prompt}]})});if(!r.ok)throw Error('claude_'+r.status);const d=await r.json();return extract(d?.content?.map(x=>x.text||'').join(''))}
async function gemini(env,prompt){if(!env.GEMINI_API_KEY)return null;const model=env.GEMINI_MODEL||'gemini-2.5-flash';const r=await fetch('https://generativelanguage.googleapis.com/v1beta/models/'+encodeURIComponent(model)+':generateContent?key='+encodeURIComponent(env.GEMINI_API_KEY),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:'You are Gemini, ANIL X research verifier. Return JSON only with ok,corrections,confidence. '+prompt}]}]})});if(!r.ok)throw Error('gemini_'+r.status);const d=await r.json();return extract(d?.candidates?.[0]?.content?.parts?.map(x=>x.text||'').join(''))}
export async function handlePlan(request,env){if(request.method==='OPTIONS')return new Response(null,{status:204,headers:H});if(request.method!=='POST')return json({ok:false,error:'method_not_allowed'},405);try{const body=await request.json();const requestText=text(body?.text||body?.request||body?.prompt);if(!requestText)return json({ok:false,error:'missing_request'},400);const fallback=localPlan(requestText);const urls=[...requestText.matchAll(/https?:\\/\\/[^\\s<>"']+/g)].map(x=>x[0]).slice(0,3);
const searchIntent=/(latest|today|news|current|price|research|search|تحقیق|جستجو|جدیدترین|امروز|قیمت|اخبار|بررسی)/i.test(requestText);
const searchResults=searchIntent?await toolWebSearch(env,requestText):null;
const toolResults=urls.length?await Promise.all(urls.map(u=>toolFetchUrl(env,u))):[];
const prompt=JSON.stringify({request:requestText,profile:body?.profile||{},conversation:body?.turns||[],fallback,toolResults,searchResults});let astra=null,claude=null,gemini=null,errors=[];try{astra=await openai(env,prompt)}catch(e){errors.push(String(e.message))}const reviewPrompt=JSON.stringify({request:requestText,plan:astra||fallback,context:body?.profile||{}});const reviews=await Promise.allSettled([claude(env,reviewPrompt),gemini(env,reviewPrompt)]); if(reviews[0].status==='fulfilled')claude=reviews[0].value;else errors.push(String(reviews[0].reason?.message||reviews[0].reason||'claude_error')); if(reviews[1].status==='fulfilled')gemini=reviews[1].value;else errors.push(String(reviews[1].reason?.message||reviews[1].reason||'gemini_error')); const reply=astra?.reply||('گرفتم: '+(astra?.title||fallback.title)); const text=reply;return json({ok:true,source:astra?'ai-council':'local-fallback',orchestrator:astra?'astra':'local',reviewer:claude?'claude':'local',research:gemini?'gemini':'local',specialists:{astra:{live:!!astra,provider:'openai'},claude:{live:!!claude,provider:'anthropic'},gemini:{live:!!gemini,provider:'google'},vision:{live:false,endpoint:'/api/vision'},voice:{live:false,endpoint:'/api/voice'}},router:{selected:astra?.specialist||fallback.title,providerErrors:errors.slice(0,4),tools:{urls:toolResults.length,used:toolResults.some(x=>x?.ok),webSearch:Boolean(searchResults?.ok),searchProvider:searchResults?.provider||null}},plan:{title:astra?.title||fallback.title,desc:astra?.desc||fallback.desc,moves:Array.isArray(astra?.moves)&&astra.moves.length?astra.moves.slice(0,6):fallback.moves},reply,text,answer:reply,confidence:Number(astra?.confidence)||.55})}catch(e){return json({ok:false,error:'engine_failure',message:String(e?.message||e)},502)}}